### ISSUE TITLE
Feat: user profile API response에 userId 추가

### ISSUE THREAD

**Issue by Turtle-Hwan** [KUIT-Space/KUIT_Space_BackEnd#120]
## 📝 이슈 설명
- user profile 받는 API에서 자신의 userId도 함께 넣어주시면 좋을 거 같아요
- 특정 유저를 판단하기 위해 userId가 자주 쓰여서 그렇습니다

## ✅ 투두리스트
- [ ]
- [ ]

**Comment by Turtle-Hwan** [comment]
후보안
- 처음 로그인 할 때 받기
- "스페이스 별 유저 프로필 조회" 에서 받기

**Comment by seongjunnoh** [comment]
> 후보안
> 
> * 처음 로그인 할 때 받기
> * "스페이스 별 유저 프로필 조회" 에서 받기

처음 로그인 할때 userId를 response에 담아주는 방식으로 코드 수정하였습니다!
jwt의 payload의 "userId" 부분의 userId 값을 사용하시는 방법도 있습니다
